<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Student extends Model
{
    use HasFactory;

    protected $table = 'dataset';

    protected $fillable = [
        'student_number',
        'gender',
        'age',
        'degree',
        'year_graduated',
        'cgpa',
        'average_prof_grade',
        'average_elec_grade',
        'ojt_grade',
        'leadership_pos',
        'act_member_pos',
        'soft_skills_ave',
        'hard_skills_ave',
        'employability',
        'auditing_skills',
        'budgeting_analysis_skills',
        'classroom_management_skills',
        'cloud_computing_skills',
        'curriculum_development_skills',
        'data_structures_algorithms',
        'database_management_skills',
        'educational_technology_skills',
        'financial_accounting_skills',
        'financial_management_skills',
        'java_programming_skills',
        'leadership_decision_making_skills',
        'machine_learning_skills',
        'marketing_skills',
        'networking_skills',
        'programming_logic_skills',
        'python_programming_skills',
        'software_engineering_skills',
        'strategic_planning_skills',
        'system_design_skills',
        'taxation_skills',
        'teaching_skills',
        'web_development_skills',
        'statistical_analysis_skills',
        'english_communication_writing_skills',
        'filipino_communication_writing_skills',
        'early_childhood_education_skills',
        'customer_service_skills',
        'event_management_skills',
        'food_beverage_management_skills',
        'risk_management_skills',
        'innovation_business_planning_skills',
        'consumer_behavior_analysis',
        'sales_management_skills',
        'artificial_intelligence_skills',
        'cybersecurity_skills',
        'circuit_design_skills',
        'communication_systems_skills',
        'problem_solving_skills',
        'clinical_skills',
        'patient_care_skills',
        'health_assessment_skills',
        'emergency_response_skills',
        'board_passer'
    ];

    protected $casts = [
        'age' => 'integer',
        'year_graduated' => 'integer',
        'cgpa' => 'decimal:2',
        'average_prof_grade' => 'decimal:2',
        'average_elec_grade' => 'decimal:2',
        'ojt_grade' => 'decimal:2',
        'soft_skills_ave' => 'decimal:2',
        'hard_skills_ave' => 'decimal:2',
        'employability' => 'string',
        'auditing_skills' => 'decimal:2',
        'budgeting_analysis_skills' => 'decimal:2',
        'classroom_management_skills' => 'decimal:2',
        'cloud_computing_skills' => 'decimal:2',
        'curriculum_development_skills' => 'decimal:2',
        'data_structures_algorithms' => 'decimal:2',
        'database_management_skills' => 'decimal:2',
        'educational_technology_skills' => 'decimal:2',
        'financial_accounting_skills' => 'decimal:2',
        'financial_management_skills' => 'decimal:2',
        'java_programming_skills' => 'decimal:2',
        'leadership_decision_making_skills' => 'decimal:2',
        'machine_learning_skills' => 'decimal:2',
        'marketing_skills' => 'decimal:2',
        'networking_skills' => 'decimal:2',
        'programming_logic_skills' => 'decimal:2',
        'python_programming_skills' => 'decimal:2',
        'software_engineering_skills' => 'decimal:2',
        'strategic_planning_skills' => 'decimal:2',
        'system_design_skills' => 'decimal:2',
        'taxation_skills' => 'decimal:2',
        'teaching_skills' => 'decimal:2',
        'web_development_skills' => 'decimal:2',
        'statistical_analysis_skills' => 'decimal:2',
        'english_communication_writing_skills' => 'decimal:2',
        'filipino_communication_writing_skills' => 'decimal:2',
        'early_childhood_education_skills' => 'decimal:2',
        'customer_service_skills' => 'decimal:2',
        'event_management_skills' => 'decimal:2',
        'food_beverage_management_skills' => 'decimal:2',
        'risk_management_skills' => 'decimal:2',
        'innovation_business_planning_skills' => 'decimal:2',
        'consumer_behavior_analysis' => 'decimal:2',
        'sales_management_skills' => 'decimal:2',
        'artificial_intelligence_skills' => 'decimal:2',
        'cybersecurity_skills' => 'decimal:2',
        'circuit_design_skills' => 'decimal:2',
        'communication_systems_skills' => 'decimal:2',
        'problem_solving_skills' => 'decimal:2',
        'clinical_skills' => 'decimal:2',
        'patient_care_skills' => 'decimal:2',
        'health_assessment_skills' => 'decimal:2',
        'emergency_response_skills' => 'decimal:2',
        'board_passer' => 'boolean'
    ];
}
